/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125homeRouteRouteImport } from './routes/{-$locale}/(home)/route'
import { Route as Char123LocaleChar125homeIndexRouteImport } from './routes/{-$locale}/(home)/index'
import { Route as Char123LocaleChar125homeAppsRouteImport } from './routes/{-$locale}/(home)/apps'
import { Route as Char123LocaleChar125homeContactRouteImport } from './routes/{-$locale}/(home)/contact'
import { Route as Char123LocaleChar125homeExploreRouteImport } from './routes/{-$locale}/(home)/explore'

const Char123LocaleChar125homeRouteRoute =
  Char123LocaleChar125homeRouteRouteImport.update({
    id: '/{-$locale}/(home)',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125homeIndexRoute =
  Char123LocaleChar125homeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125homeRouteRoute,
  } as any)
const Char123LocaleChar125homeAppsRoute =
  Char123LocaleChar125homeAppsRouteImport.update({
    id: '/apps',
    path: '/apps',
    getParentRoute: () => Char123LocaleChar125homeRouteRoute,
  } as any)
const Char123LocaleChar125homeContactRoute =
  Char123LocaleChar125homeContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LocaleChar125homeRouteRoute,
  } as any)
const Char123LocaleChar125homeExploreRoute =
  Char123LocaleChar125homeExploreRouteImport.update({
    id: '/explore',
    path: '/explore',
    getParentRoute: () => Char123LocaleChar125homeRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125homeRouteRouteWithChildren
  '/{-$locale}/apps': typeof Char123LocaleChar125homeAppsRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125homeContactRoute
  '/{-$locale}/explore': typeof Char123LocaleChar125homeExploreRoute
  '/{-$locale}/': typeof Char123LocaleChar125homeIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/apps': typeof Char123LocaleChar125homeAppsRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125homeContactRoute
  '/{-$locale}/explore': typeof Char123LocaleChar125homeExploreRoute
  '/{-$locale}': typeof Char123LocaleChar125homeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}/(home)': typeof Char123LocaleChar125homeRouteRouteWithChildren
  '/{-$locale}/(home)/apps': typeof Char123LocaleChar125homeAppsRoute
  '/{-$locale}/(home)/contact': typeof Char123LocaleChar125homeContactRoute
  '/{-$locale}/(home)/explore': typeof Char123LocaleChar125homeExploreRoute
  '/{-$locale}/(home)/': typeof Char123LocaleChar125homeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/apps'
    | '/{-$locale}/contact'
    | '/{-$locale}/explore'
    | '/{-$locale}/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/apps'
    | '/{-$locale}/contact'
    | '/{-$locale}/explore'
    | '/{-$locale}'
  id:
    | '__root__'
    | '/{-$locale}/(home)'
    | '/{-$locale}/(home)/apps'
    | '/{-$locale}/(home)/contact'
    | '/{-$locale}/(home)/explore'
    | '/{-$locale}/(home)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125homeRouteRoute: typeof Char123LocaleChar125homeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}/(home)': {
      id: '/{-$locale}/(home)'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125homeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/(home)/': {
      id: '/{-$locale}/(home)/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125homeIndexRouteImport
      parentRoute: typeof Char123LocaleChar125homeRouteRoute
    }
    '/{-$locale}/(home)/apps': {
      id: '/{-$locale}/(home)/apps'
      path: '/apps'
      fullPath: '/{-$locale}/apps'
      preLoaderRoute: typeof Char123LocaleChar125homeAppsRouteImport
      parentRoute: typeof Char123LocaleChar125homeRouteRoute
    }
    '/{-$locale}/(home)/contact': {
      id: '/{-$locale}/(home)/contact'
      path: '/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125homeContactRouteImport
      parentRoute: typeof Char123LocaleChar125homeRouteRoute
    }
    '/{-$locale}/(home)/explore': {
      id: '/{-$locale}/(home)/explore'
      path: '/explore'
      fullPath: '/{-$locale}/explore'
      preLoaderRoute: typeof Char123LocaleChar125homeExploreRouteImport
      parentRoute: typeof Char123LocaleChar125homeRouteRoute
    }
  }
}

interface Char123LocaleChar125homeRouteRouteChildren {
  Char123LocaleChar125homeAppsRoute: typeof Char123LocaleChar125homeAppsRoute
  Char123LocaleChar125homeContactRoute: typeof Char123LocaleChar125homeContactRoute
  Char123LocaleChar125homeExploreRoute: typeof Char123LocaleChar125homeExploreRoute
  Char123LocaleChar125homeIndexRoute: typeof Char123LocaleChar125homeIndexRoute
}

const Char123LocaleChar125homeRouteRouteChildren: Char123LocaleChar125homeRouteRouteChildren =
  {
    Char123LocaleChar125homeAppsRoute: Char123LocaleChar125homeAppsRoute,
    Char123LocaleChar125homeContactRoute: Char123LocaleChar125homeContactRoute,
    Char123LocaleChar125homeExploreRoute: Char123LocaleChar125homeExploreRoute,
    Char123LocaleChar125homeIndexRoute: Char123LocaleChar125homeIndexRoute,
  }

const Char123LocaleChar125homeRouteRouteWithChildren =
  Char123LocaleChar125homeRouteRoute._addFileChildren(
    Char123LocaleChar125homeRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125homeRouteRoute:
    Char123LocaleChar125homeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
